-- 음식 추천 agent 풀 E2E용 더미 시드
-- ============================================
-- 빈 DB 가정. user(id=5) + foods 8종 + grades + meals + glucose.
-- 멱등 안전 (ON CONFLICT). 시연 user_id=5 고정.
--
-- 적용:
--   docker compose exec -T postgres psql -U ssafy -d s309 < ai/scripts/seed_food_recommend_full.sql

\set demo_user_id 5

-- ── 1. users (id=5 강제) ─────────────────────────────────
-- IDENTITY 컬럼이지만 GENERATED BY DEFAULT라 명시 INSERT 가능.

INSERT INTO users (id, email, password, provider, name, age, gender, phone,
                   height, weight, diabetes_type, is_medicated, target_low, target_high)
VALUES (:demo_user_id, 'demo5@glucocoach.local', NULL, 'email', '시연유저5',
        45, 'M', '010-0000-0005', 173.0, 78.0, 'T2D', true, 70.0, 180.0)
ON CONFLICT (id) DO UPDATE
   SET age = EXCLUDED.age, gender = EXCLUDED.gender,
       diabetes_type = EXCLUDED.diabetes_type, is_medicated = EXCLUDED.is_medicated,
       target_low = EXCLUDED.target_low, target_high = EXCLUDED.target_high,
       height = EXCLUDED.height, weight = EXCLUDED.weight;

-- IDENTITY 시퀀스 보정 (수동 INSERT 후 다음 자동 생성 충돌 방지)
SELECT setval(pg_get_serial_sequence('users', 'id'),
              GREATEST((SELECT MAX(id) FROM users), 1));

-- ── 2. foods (8종 — 식약처 API 안 거치고 직접 입력) ───────
-- food_api_id NULL 허용, name UNIQUE 아니므로 NOT EXISTS 가드.

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '현미밥', '밥류', 350.00, 75.00, 7.50, 2.50, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '현미밥');

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '닭가슴살 샐러드', '샐러드', 280.00, 20.00, 35.00, 8.00, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '닭가슴살 샐러드');

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '두부조림', '반찬', 180.00, 10.00, 18.00, 9.00, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '두부조림');

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '고등어구이', '생선', 320.00, 0.50, 28.00, 22.00, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '고등어구이');

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '잡곡밥', '밥류', 360.00, 76.00, 8.00, 2.20, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '잡곡밥');

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '쌀밥', '밥류', 380.00, 84.00, 6.50, 1.00, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '쌀밥');

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '라면', '면류', 500.00, 80.00, 11.00, 16.00, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '라면');

INSERT INTO foods (name, category, kcal, carbs_g, protein_g, fat_g, is_customized)
SELECT '떡볶이', '분식', 480.00, 95.00, 8.00, 5.00, true
WHERE NOT EXISTS (SELECT 1 FROM foods WHERE name = '떡볶이');

-- ── 3. user_food_grades ───────────────────────────────────

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 1.2, 'S', 8 FROM foods f WHERE f.name = '현미밥' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 1.4, 'S', 6 FROM foods f WHERE f.name = '닭가슴살 샐러드' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 1.8, 'A', 5 FROM foods f WHERE f.name = '두부조림' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 2.0, 'A', 4 FROM foods f WHERE f.name = '고등어구이' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 2.5, 'B', 5 FROM foods f WHERE f.name = '잡곡밥' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 3.5, 'C', 7 FROM foods f WHERE f.name = '쌀밥' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 4.8, 'D', 3 FROM foods f WHERE f.name = '라면' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

INSERT INTO user_food_grades (user_id, food_id, avg_slope, grade, meal_count)
SELECT :demo_user_id, f.id, 5.1, 'D', 2 FROM foods f WHERE f.name = '떡볶이' LIMIT 1
ON CONFLICT (user_id, food_id) DO UPDATE
   SET avg_slope = EXCLUDED.avg_slope, grade = EXCLUDED.grade, meal_count = EXCLUDED.meal_count, updated_at = CURRENT_TIMESTAMP;

-- ── 4. meal_records (최근 3건) ───────────────────────────

INSERT INTO meal_records (user_id, food_id, image_origin_name, image_storage_key, is_processed, memo, recorded_at)
SELECT :demo_user_id, f.id, NULL, NULL, true, '시연 시드', CURRENT_TIMESTAMP - INTERVAL '3 hours'
FROM foods f WHERE f.name = '현미밥'
  AND NOT EXISTS (SELECT 1 FROM meal_records m WHERE m.user_id = :demo_user_id AND m.recorded_at = CURRENT_TIMESTAMP - INTERVAL '3 hours')
LIMIT 1;

INSERT INTO meal_records (user_id, food_id, image_origin_name, image_storage_key, is_processed, memo, recorded_at)
SELECT :demo_user_id, f.id, NULL, NULL, true, '시연 시드', CURRENT_TIMESTAMP - INTERVAL '20 hours'
FROM foods f WHERE f.name = '닭가슴살 샐러드'
  AND NOT EXISTS (SELECT 1 FROM meal_records m WHERE m.user_id = :demo_user_id AND m.recorded_at = CURRENT_TIMESTAMP - INTERVAL '20 hours')
LIMIT 1;

INSERT INTO meal_records (user_id, food_id, image_origin_name, image_storage_key, is_processed, memo, recorded_at)
SELECT :demo_user_id, f.id, NULL, NULL, true, '시연 시드', CURRENT_TIMESTAMP - INTERVAL '28 hours'
FROM foods f WHERE f.name = '쌀밥'
  AND NOT EXISTS (SELECT 1 FROM meal_records m WHERE m.user_id = :demo_user_id AND m.recorded_at = CURRENT_TIMESTAMP - INTERVAL '28 hours')
LIMIT 1;

-- ── 5. glucose_records (최근 3개) ────────────────────────

INSERT INTO glucose_records (user_id, value, measured_at)
SELECT :demo_user_id, 138.0, CURRENT_TIMESTAMP - INTERVAL '5 minutes'
WHERE NOT EXISTS (SELECT 1 FROM glucose_records g WHERE g.user_id = :demo_user_id AND g.measured_at = CURRENT_TIMESTAMP - INTERVAL '5 minutes');

INSERT INTO glucose_records (user_id, value, measured_at)
SELECT :demo_user_id, 135.0, CURRENT_TIMESTAMP - INTERVAL '20 minutes'
WHERE NOT EXISTS (SELECT 1 FROM glucose_records g WHERE g.user_id = :demo_user_id AND g.measured_at = CURRENT_TIMESTAMP - INTERVAL '20 minutes');

INSERT INTO glucose_records (user_id, value, measured_at)
SELECT :demo_user_id, 142.0, CURRENT_TIMESTAMP - INTERVAL '40 minutes'
WHERE NOT EXISTS (SELECT 1 FROM glucose_records g WHERE g.user_id = :demo_user_id AND g.measured_at = CURRENT_TIMESTAMP - INTERVAL '40 minutes');

-- ── 검증 ─────────────────────────────────────────────────
SELECT 'users'          AS tbl, COUNT(*) AS rows FROM users           WHERE id = :demo_user_id
UNION ALL
SELECT 'foods'          , COUNT(*)               FROM foods           WHERE name IN ('현미밥','닭가슴살 샐러드','두부조림','고등어구이','잡곡밥','쌀밥','라면','떡볶이')
UNION ALL
SELECT 'food_grades'    , COUNT(*)               FROM user_food_grades WHERE user_id = :demo_user_id
UNION ALL
SELECT 'meal_records'   , COUNT(*)               FROM meal_records    WHERE user_id = :demo_user_id AND recorded_at > CURRENT_TIMESTAMP - INTERVAL '2 days'
UNION ALL
SELECT 'glucose_records', COUNT(*)               FROM glucose_records WHERE user_id = :demo_user_id AND measured_at > CURRENT_TIMESTAMP - INTERVAL '1 hour';
