-- =============================================================
-- V10: chat_messages 테이블 신설
--
-- 목적:
--   식후/기상 후 Agent 추천을 채팅 형태로 양방향 표현.
--   alerts는 트리거/타입 카탈로그 + dedup 인프라로 유지하고,
--   사용자가 실제로 보고 응답하는 메시지 본문은 chat_messages가 단일 출처.
--
-- 양방향 흐름:
--   sender='agent' — POST /api/agent/notifications 시 alerts INSERT와 함께 chat_messages INSERT
--                    display_trace 컬럼에 AI 추론 과정(summary/cards/decision) 저장
--   sender='user'  — POST /api/chat/messages/reply 시 사용자 자유 텍스트 응답 INSERT
--                    schedule_followup 재트리거는 기존 경로 유지, chat 저장만 추가
--
-- alert_id:
--   같은 추천 사이클에 속한 메시지(agent 발신 + user 응답)를 묶기 위한 FK.
--   reply API는 alert_id로 컨텍스트 식별 → 해당 alert 소유자 검증 후 INSERT.
--   ON DELETE SET NULL — alert가 삭제돼도 채팅 히스토리는 유지.
--
-- display_trace (JSONB):
--   agent 메시지일 때만 채워짐. 구조:
--     { "summary": "...", "cards": [{type,title,description}, ...], "decision": {"reason":"..."} }
--   user 메시지에서는 NULL.
--
-- id BIGINT:
--   채팅 메시지는 alerts/sleep_sessions보다 cardinality가 훨씬 높음(N대화/일).
--   alerts는 INT 유지, chat_messages만 BIGINT.
-- =============================================================

CREATE TABLE chat_messages (
    id             BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id        INT          NOT NULL,
    sender         VARCHAR(10)  NOT NULL,
    message        TEXT         NOT NULL,
    alert_id       INT          NULL,
    display_trace  JSONB        NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_chat_messages         PRIMARY KEY (id),
    CONSTRAINT fk_chat_messages_user    FOREIGN KEY (user_id)  REFERENCES users  (id),
    CONSTRAINT fk_chat_messages_alert   FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE SET NULL,
    CONSTRAINT ck_chat_messages_sender  CHECK (sender IN ('agent', 'user'))
);

-- 본인 채팅 페이징 조회 (최신순)
CREATE INDEX idx_chat_messages_user_created
    ON chat_messages (user_id, created_at DESC);

-- alert_id로 사이클 내 메시지 묶음 조회
CREATE INDEX idx_chat_messages_alert
    ON chat_messages (alert_id)
    WHERE alert_id IS NOT NULL;

COMMENT ON TABLE  chat_messages                IS '식후/기상 후 Agent 추천 채팅 (양방향: agent ↔ user)';
COMMENT ON COLUMN chat_messages.sender         IS 'agent=Agent 발신, user=사용자 응답';
COMMENT ON COLUMN chat_messages.alert_id       IS '연결된 alerts.id — 같은 추천 사이클 묶음 식별';
COMMENT ON COLUMN chat_messages.display_trace  IS 'agent 메시지의 AI 추론 과정(summary/cards/decision). user 메시지는 NULL';
