-- =============================================================
-- V1: 통합 초기 스키마 (PostgreSQL)
-- -------------------------------------------------------------
-- 본 V1은 기존 V1~V6 마이그레이션을 모두 통합 + ERD 정합성 결정사항
-- 일괄 반영한 단일 마이그레이션입니다.
--
-- ERD.sql(backend/docs/ERD.sql)과 1:1 일치하며,
-- ddl-auto: validate 모드와 함께 동작합니다.
--
-- 적용 후 16개 테이블이 한 번에 생성됩니다.
-- =============================================================


-- ────────────────────────────────────────────
-- 1. users
-- ────────────────────────────────────────────
CREATE TABLE users (
    id              INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email           VARCHAR(255)    NOT NULL,
    password        VARCHAR(60)     NULL,
    provider        VARCHAR(10)     NOT NULL DEFAULT 'email',
    name            VARCHAR(20)     NOT NULL,
    age             SMALLINT        NULL,
    gender          VARCHAR(6)      NULL,
    phone           VARCHAR(20)     NOT NULL,
    height          NUMERIC(4,1)    NULL,
    weight          NUMERIC(4,1)    NULL,
    diabetes_type   VARCHAR(10)     NULL DEFAULT 'NORMAL',
    is_medicated    BOOLEAN         NULL,
    target_low      NUMERIC(5,2)    NULL DEFAULT 70,
    target_high     NUMERIC(5,2)    NULL DEFAULT 140,
    week_start_day  SMALLINT        NOT NULL DEFAULT 1,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP       NULL,
    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);


-- ────────────────────────────────────────────
-- 2. foods
-- ────────────────────────────────────────────
CREATE TABLE foods (
    id                 INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    food_api_id        VARCHAR(64)  NULL,
    name               VARCHAR(100) NOT NULL,
    category           VARCHAR(50)  NULL,
    kcal               NUMERIC(6,2) NULL,
    carbs_g            NUMERIC(5,2) NULL,
    sugar_g            NUMERIC(5,2) NULL,
    protein_g          NUMERIC(5,2) NULL,
    fat_g              NUMERIC(5,2) NULL,
    fiber_g            NUMERIC(5,2) NULL,
    saturated_fat_g    NUMERIC(5,2) NULL,
    trans_fat_g        NUMERIC(5,2) NULL,
    cholesterol_mg     NUMERIC(5,2) NULL,
    sodium_mg          NUMERIC(5,2) NULL,
    serving_size       NUMERIC(5,2) NULL,
    is_customized      BOOLEAN      NOT NULL DEFAULT FALSE,
    search_count       INT          NOT NULL DEFAULT 0,
    cached_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_foods             PRIMARY KEY (id),
    CONSTRAINT uq_foods_food_api_id UNIQUE (food_api_id)
);
CREATE INDEX idx_foods_name      ON foods (name);
CREATE INDEX idx_foods_category  ON foods (category);
CREATE INDEX idx_foods_cached_at ON foods (cached_at);

COMMENT ON COLUMN foods.food_api_id    IS '식약처 식품코드 (foodCd). 사용자 커스텀 음식은 NULL';
COMMENT ON COLUMN foods.category       IS '식품 대분류명 (foodLv3Nm)';
COMMENT ON COLUMN foods.kcal           IS '에너지 (kcal/100g, enerc)';
COMMENT ON COLUMN foods.carbs_g        IS '탄수화물 (g/100g, chocdf)';
COMMENT ON COLUMN foods.sugar_g        IS '당류 (g/100g, sugar)';
COMMENT ON COLUMN foods.protein_g      IS '단백질 (g/100g, prot)';
COMMENT ON COLUMN foods.fat_g          IS '지방 (g/100g, fatce)';
COMMENT ON COLUMN foods.fiber_g        IS '식이섬유 (g/100g, fibtg)';
COMMENT ON COLUMN foods.saturated_fat_g IS '포화지방 (g/100g, fasat)';
COMMENT ON COLUMN foods.trans_fat_g    IS '트랜스지방 (g/100g, fatrn)';
COMMENT ON COLUMN foods.cholesterol_mg IS '콜레스테롤 (mg/100g, chole)';
COMMENT ON COLUMN foods.sodium_mg      IS '나트륨 (mg/100g, nat)';
COMMENT ON COLUMN foods.serving_size   IS '1회 제공량 기준치 (식약처 캐시는 100 고정, 커스텀은 입력값)';
COMMENT ON COLUMN foods.is_customized  IS '사용자가 등록한 음식인지 (음식 인식 실패 시 텍스트 입력)';
COMMENT ON COLUMN foods.search_count   IS '검색 히트 횟수 (캐시 우선순위)';
COMMENT ON COLUMN foods.cached_at      IS '식약처 API 마지막 호출 시각 (30일 TTL 기준)';


-- ────────────────────────────────────────────
-- 3. glucose_records
-- ────────────────────────────────────────────
CREATE TABLE glucose_records (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     INT          NOT NULL,
    value       NUMERIC(5,2) NOT NULL,
    measured_at TIMESTAMP    NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_glucose_records PRIMARY KEY (id),
    CONSTRAINT fk_glucose_user    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_glucose_user_time ON glucose_records (user_id, measured_at);

COMMENT ON COLUMN glucose_records.value       IS '혈당값 (mg/dL)';
COMMENT ON COLUMN glucose_records.measured_at IS 'CGM 디바이스 측정 시각 (서버 tz=KST)';


-- ────────────────────────────────────────────
-- 4. meal_records
-- ────────────────────────────────────────────
CREATE TABLE meal_records (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           INT          NOT NULL,
    food_id           INT          NULL,
    image_origin_name VARCHAR(255) NULL,
    image_storage_key VARCHAR(255) NULL,
    is_processed      BOOLEAN      NOT NULL DEFAULT FALSE,
    memo              VARCHAR(255) NULL,
    recorded_at       TIMESTAMP    NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_meal_records PRIMARY KEY (id),
    CONSTRAINT fk_meal_user    FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_meal_food    FOREIGN KEY (food_id) REFERENCES foods (id)
);
CREATE INDEX idx_meal_user_time ON meal_records (user_id, recorded_at);

COMMENT ON COLUMN meal_records.food_id           IS '수동 입력 시 NULL';
COMMENT ON COLUMN meal_records.image_storage_key IS 'S3 등 외부 스토리지 키';
COMMENT ON COLUMN meal_records.recorded_at       IS '실제 식사 시각 (서버 tz=KST)';


-- ────────────────────────────────────────────
-- 5. meal_glucose_responses
-- ────────────────────────────────────────────
CREATE TABLE meal_glucose_responses (
    id                  INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id             INT          NOT NULL,
    meal_id             INT          NOT NULL,
    baseline_glucose_id BIGINT       NOT NULL,
    peak_glucose_id     BIGINT       NOT NULL,
    slope               NUMERIC(3,1) NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_meal_glucose_responses PRIMARY KEY (id),
    CONSTRAINT uq_response_meal     UNIQUE (meal_id),
    CONSTRAINT fk_response_user     FOREIGN KEY (user_id)             REFERENCES users (id),
    CONSTRAINT fk_response_meal     FOREIGN KEY (meal_id)             REFERENCES meal_records (id),
    CONSTRAINT fk_response_baseline FOREIGN KEY (baseline_glucose_id) REFERENCES glucose_records (id),
    CONSTRAINT fk_response_peak     FOREIGN KEY (peak_glucose_id)     REFERENCES glucose_records (id)
);
CREATE INDEX idx_response_user ON meal_glucose_responses (user_id);

COMMENT ON COLUMN meal_glucose_responses.baseline_glucose_id IS '식전 혈당';
COMMENT ON COLUMN meal_glucose_responses.peak_glucose_id     IS '식후 2시간 내 최고 혈당';
COMMENT ON COLUMN meal_glucose_responses.slope               IS '상승 기울기 (mg/dL/min) — 등급 산출 기준';


-- ────────────────────────────────────────────
-- 6. glucose_predictions
-- ────────────────────────────────────────────
CREATE TABLE glucose_predictions (
    id              INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id         INT          NOT NULL,
    food_id         INT          NULL,
    food_name       VARCHAR(100) NULL,
    predicted_curve JSON         NOT NULL,
    predicted_peak  NUMERIC(5,2) NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_glucose_predictions PRIMARY KEY (id),
    CONSTRAINT fk_prediction_user     FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_prediction_food     FOREIGN KEY (food_id) REFERENCES foods (id)
);
CREATE INDEX idx_prediction_user_time ON glucose_predictions (user_id, created_at);

COMMENT ON COLUMN glucose_predictions.food_id         IS '음식 DB에 없는 데이터인 경우 NULL';
COMMENT ON COLUMN glucose_predictions.food_name       IS 'food_id 없을 때 수기 입력';
COMMENT ON COLUMN glucose_predictions.predicted_curve IS '예측 곡선 [{minuteOffset, glucoseMgdl}, ...]';
COMMENT ON COLUMN glucose_predictions.predicted_peak  IS '예측 최고 혈당 (mg/dL)';


-- ────────────────────────────────────────────
-- 7. user_food_grades
-- ────────────────────────────────────────────
CREATE TABLE user_food_grades (
    id         INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    INT          NOT NULL,
    food_id    INT          NOT NULL,
    avg_slope  NUMERIC(3,1) NOT NULL,
    grade      CHAR(1)      NOT NULL,
    meal_count INT          NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_food_grades PRIMARY KEY (id),
    CONSTRAINT uq_user_food         UNIQUE (user_id, food_id),
    CONSTRAINT fk_grade_user        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_grade_food        FOREIGN KEY (food_id) REFERENCES foods (id),
    CONSTRAINT ck_user_food_grade   CHECK (grade IN ('S','A','B','C','D'))
);

COMMENT ON COLUMN user_food_grades.avg_slope  IS 'meal_glucose_responses.slope 평균';
COMMENT ON COLUMN user_food_grades.grade      IS 'S / A / B / C / D';
COMMENT ON COLUMN user_food_grades.meal_count IS '평균 산정에 사용된 식사 횟수';


-- ────────────────────────────────────────────
-- 8. weekly_reports
-- ────────────────────────────────────────────
CREATE TABLE weekly_reports (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           INT          NOT NULL,
    week_start        DATE         NULL DEFAULT CURRENT_DATE,
    avg_glucose       NUMERIC(5,2) NULL,
    min_glucose       NUMERIC(5,2) NULL,
    max_glucose       NUMERIC(5,2) NULL,
    glucose_sd        NUMERIC(5,2) NULL,
    time_in_range     NUMERIC(5,2) NULL,
    time_above_range  NUMERIC(5,2) NULL,
    time_below_range  NUMERIC(5,2) NULL,
    ai_summary        TEXT         NULL,
    ai_suggest        TEXT         NULL,
    pdf_key           VARCHAR(100) NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_weekly_reports PRIMARY KEY (id),
    CONSTRAINT fk_report_user    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_report_user_week ON weekly_reports (user_id, week_start);

COMMENT ON COLUMN weekly_reports.week_start       IS '리포트 커버 시작일';
COMMENT ON COLUMN weekly_reports.avg_glucose      IS '주간 평균 혈당 (mg/dL)';
COMMENT ON COLUMN weekly_reports.glucose_sd       IS '혈당 표준편차 (변동 폭)';
COMMENT ON COLUMN weekly_reports.time_in_range    IS '목표 범위 내 비율 TIR (%)';
COMMENT ON COLUMN weekly_reports.time_above_range IS '고혈당 비율 TAR (%)';
COMMENT ON COLUMN weekly_reports.time_below_range IS '저혈당 비율 TBR (%)';
COMMENT ON COLUMN weekly_reports.ai_summary       IS 'LLM 생성 주간 요약';
COMMENT ON COLUMN weekly_reports.ai_suggest       IS 'LLM 생성 개선 제안';
COMMENT ON COLUMN weekly_reports.pdf_key          IS 'S3 PDF 키 (예: reports/user_1/week_1.pdf)';


-- ────────────────────────────────────────────
-- 9. weekly_foods
-- ────────────────────────────────────────────
CREATE TABLE weekly_foods (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    report_id         INT          NOT NULL,
    food_id           INT          NOT NULL,
    type              VARCHAR(4)   NOT NULL,
    image_storage_key VARCHAR(255) NULL,
    avg_slope         NUMERIC(3,1) NOT NULL,
    CONSTRAINT pk_weekly_foods       PRIMARY KEY (id),
    CONSTRAINT fk_weekly_food_report FOREIGN KEY (report_id) REFERENCES weekly_reports (id),
    CONSTRAINT fk_weekly_food_food   FOREIGN KEY (food_id)   REFERENCES foods (id),
    CONSTRAINT ck_weekly_food_type   CHECK (type IN ('GOOD','BAD'))
);
CREATE INDEX idx_weekly_food_report ON weekly_foods (report_id);

COMMENT ON COLUMN weekly_foods.type              IS 'GOOD / BAD';
COMMENT ON COLUMN weekly_foods.image_storage_key IS '주 중 마지막에 먹은 음식 사진 (없을 수 있음)';
COMMENT ON COLUMN weekly_foods.avg_slope         IS '해당 주 해당 음식 평균 기울기';


-- ────────────────────────────────────────────
-- 10. notification_tokens
-- ────────────────────────────────────────────
CREATE TABLE notification_tokens (
    id          INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     INT          NOT NULL,
    token       VARCHAR(200) NOT NULL,
    device_type VARCHAR(10)  NOT NULL DEFAULT 'ANDROID',
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notification_tokens PRIMARY KEY (id),
    CONSTRAINT fk_noti_user           FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_noti_device_type    CHECK (device_type IN ('ANDROID','WATCH'))
);
CREATE INDEX idx_noti_user_active ON notification_tokens (user_id, is_active);

COMMENT ON COLUMN notification_tokens.token     IS 'FCM 토큰 값';
COMMENT ON COLUMN notification_tokens.is_active IS '로그아웃 시 false';


-- ────────────────────────────────────────────
-- 11. alerts
-- ────────────────────────────────────────────
CREATE TABLE alerts (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           INT          NOT NULL,
    alert_type        VARCHAR(20)  NOT NULL,
    glucose_record_id BIGINT       NULL,
    weekly_report_id  INT          NULL,
    message           VARCHAR(100) NULL,
    latitude          NUMERIC(9,6) NULL,
    longitude         NUMERIC(9,6) NULL,
    is_read           BOOLEAN      NOT NULL DEFAULT FALSE,
    resolved_at       TIMESTAMP    NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMP    NULL,
    CONSTRAINT pk_alerts        PRIMARY KEY (id),
    CONSTRAINT fk_alert_user    FOREIGN KEY (user_id)           REFERENCES users (id),
    CONSTRAINT fk_alert_glucose FOREIGN KEY (glucose_record_id) REFERENCES glucose_records (id),
    CONSTRAINT fk_alert_report  FOREIGN KEY (weekly_report_id)  REFERENCES weekly_reports (id),
    CONSTRAINT ck_alerts_type   CHECK (alert_type IN ('HIGH','LOW','SOS','WEEKLY_REPORT'))
);
CREATE INDEX idx_alert_user_time ON alerts (user_id, created_at);

COMMENT ON COLUMN alerts.alert_type        IS 'HIGH / LOW / SOS / WEEKLY_REPORT';
COMMENT ON COLUMN alerts.glucose_record_id IS 'HIGH/LOW/SOS 트리거 측정';
COMMENT ON COLUMN alerts.weekly_report_id  IS '리포트 알림 대상';
COMMENT ON COLUMN alerts.latitude          IS 'SOS 발송 시 GPS 위도';
COMMENT ON COLUMN alerts.longitude         IS 'SOS 발송 시 GPS 경도';
COMMENT ON COLUMN alerts.resolved_at       IS '혈당 정상 복귀 / SOS 응답 / 사용자 확인';


-- ────────────────────────────────────────────
-- 12. ward_guardian
-- ────────────────────────────────────────────
CREATE TABLE ward_guardian (
    id          INT         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ward_id     INT         NOT NULL,
    guardian_id INT         NOT NULL,
    relation    VARCHAR(10) NULL,
    priority    SMALLINT    NOT NULL,
    CONSTRAINT pk_ward_guardian PRIMARY KEY (id),
    CONSTRAINT fk_wg_ward       FOREIGN KEY (ward_id)     REFERENCES users (id),
    CONSTRAINT fk_wg_guardian   FOREIGN KEY (guardian_id) REFERENCES users (id)
);
CREATE INDEX idx_wg_ward     ON ward_guardian (ward_id);
CREATE INDEX idx_wg_guardian ON ward_guardian (guardian_id);

COMMENT ON COLUMN ward_guardian.ward_id     IS '피보호자';
COMMENT ON COLUMN ward_guardian.guardian_id IS '보호자';
COMMENT ON COLUMN ward_guardian.relation    IS '부모 / 배우자 / 자녀 등';
COMMENT ON COLUMN ward_guardian.priority    IS '0이 1순위 (SOS 연락 순서)';


-- ────────────────────────────────────────────
-- 13. guardian_notifications
-- ────────────────────────────────────────────
CREATE TABLE guardian_notifications (
    id                INT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    alert_id          INT       NOT NULL,
    guard_relation_id INT       NOT NULL,
    sent_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at      TIMESTAMP NULL,
    CONSTRAINT pk_guardian_notifications PRIMARY KEY (id),
    CONSTRAINT fk_gn_alert    FOREIGN KEY (alert_id)          REFERENCES alerts (id),
    CONSTRAINT fk_gn_relation FOREIGN KEY (guard_relation_id) REFERENCES ward_guardian (id)
);
CREATE INDEX idx_gn_alert    ON guardian_notifications (alert_id);
CREATE INDEX idx_gn_relation ON guardian_notifications (guard_relation_id);

COMMENT ON COLUMN guardian_notifications.alert_id          IS '어떤 SOS인지';
COMMENT ON COLUMN guardian_notifications.guard_relation_id IS 'ward_guardian.id 참조';
COMMENT ON COLUMN guardian_notifications.sent_at           IS 'created_at 역할, 미응답 판정 기준';
COMMENT ON COLUMN guardian_notifications.responded_at      IS 'NULL이면 미응답';


-- ────────────────────────────────────────────
-- 14. medications_records
-- ────────────────────────────────────────────
CREATE TABLE medications_records (
    id         INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    INT          NOT NULL,
    memo       VARCHAR(200) NULL,
    taken_at   TIMESTAMP    NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_medications_records PRIMARY KEY (id),
    CONSTRAINT fk_med_user            FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_med_user_time ON medications_records (user_id, taken_at);

COMMENT ON COLUMN medications_records.memo IS '약 이름, 세부사항 등 자유 기술';


-- ────────────────────────────────────────────
-- 15. sleep_records
-- ────────────────────────────────────────────
CREATE TABLE sleep_records (
    id         INT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    INT       NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at   TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sleep_records PRIMARY KEY (id),
    CONSTRAINT fk_sleep_user    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_sleep_user_time ON sleep_records (user_id, started_at);


-- ────────────────────────────────────────────
-- 16. exercise_records
-- ────────────────────────────────────────────
CREATE TABLE exercise_records (
    id            INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       INT          NOT NULL,
    exercise_type VARCHAR(20)  NOT NULL,
    calories      NUMERIC(6,2) NULL,
    started_at    TIMESTAMP    NOT NULL,
    ended_at      TIMESTAMP    NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_exercise_records PRIMARY KEY (id),
    CONSTRAINT fk_ex_user          FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_ex_user_time ON exercise_records (user_id, started_at);

COMMENT ON COLUMN exercise_records.exercise_type IS 'WALKING / RUNNING / CYCLING 등';
COMMENT ON COLUMN exercise_records.calories      IS '소모 칼로리 (kcal)';