-- =============================================================
-- V1: 초기 스키마 (JPA 엔티티 기준, BIGINT IDENTITY PK)
-- =============================================================

-- ────────────────────────────────────────────
-- users
-- ────────────────────────────────────────────
CREATE TABLE users (
    id             BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email          VARCHAR(255)  NOT NULL,
    password       VARCHAR(255)  NULL,
    provider       VARCHAR(10)   NOT NULL DEFAULT 'email',
    name           VARCHAR(20)   NULL,
    age            SMALLINT      NULL,
    gender         VARCHAR(6)    NULL,
    phone          VARCHAR(20)   NULL,
    height         FLOAT         NULL,
    weight         FLOAT         NULL,
    diabetes_type  VARCHAR(10)   NULL,
    is_medicated   BOOLEAN       NULL,
    target_low     INT           NULL,
    target_high    INT           NULL,
    week_start_day SMALLINT      NOT NULL DEFAULT 1,
    deleted_at     TIMESTAMP     NULL,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ────────────────────────────────────────────
-- ward_guardian
-- ────────────────────────────────────────────
CREATE TABLE ward_guardian (
    id          BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ward_id     BIGINT      NOT NULL,
    guardian_id BIGINT      NOT NULL,
    relation    VARCHAR(10) NULL,
    priority    SMALLINT    NOT NULL DEFAULT 0,
    CONSTRAINT pk_ward_guardian  PRIMARY KEY (id),
    CONSTRAINT fk_wg_ward        FOREIGN KEY (ward_id)     REFERENCES users (id),
    CONSTRAINT fk_wg_guardian    FOREIGN KEY (guardian_id) REFERENCES users (id)
);
CREATE INDEX idx_wg_ward     ON ward_guardian (ward_id);
CREATE INDEX idx_wg_guardian ON ward_guardian (guardian_id);

-- ────────────────────────────────────────────
-- notification_tokens
-- ────────────────────────────────────────────
CREATE TABLE notification_tokens (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(200) NOT NULL,
    device_type VARCHAR(10)  NOT NULL DEFAULT 'android',
    is_active   BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notification_tokens PRIMARY KEY (id),
    CONSTRAINT fk_nt_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_noti_user_active ON notification_tokens (user_id, is_active);

-- ────────────────────────────────────────────
-- glucose_predictions
-- ────────────────────────────────────────────
CREATE TABLE glucose_predictions (
    id              INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT       NOT NULL,
    food_id         INT          NULL,
    food_name       VARCHAR(100) NULL,
    predicted_curve JSON         NOT NULL,
    predicted_peak  NUMERIC(5,2) NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_glucose_predictions PRIMARY KEY (id),
    CONSTRAINT fk_gp_user FOREIGN KEY (user_id) REFERENCES users (id)
);
