-- =============================================================
-- V3: health_snapshots 테이블 신설 (wide-format 시계열)
--   - 1분 polling으로 모인 4개 메트릭(steps, calories, heart_rate)을
--     5분 batch로 한 번에 append (sleep은 daily 집계라 daily_health_summaries에 잔류)
--   - ON CONFLICT (user_id, recorded_at) DO NOTHING — 멱등 보장
--   - Agent 쿼리: 메트릭별 MAX-MIN 또는 AVG (counter-rate / instantaneous 혼합)
-- =============================================================

CREATE TABLE health_snapshots (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id         INT          NOT NULL,
    recorded_at     TIMESTAMP    NOT NULL,
    steps_total     INT          NULL,
    calories_burned NUMERIC(6,2) NULL,
    heart_rate      NUMERIC(5,1) NULL,
    CONSTRAINT pk_health_snapshots          PRIMARY KEY (id),
    CONSTRAINT uq_snapshot_user_time        UNIQUE (user_id, recorded_at),
    CONSTRAINT fk_snapshot_user             FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_snapshot_steps_nonneg    CHECK (steps_total IS NULL OR steps_total >= 0),
    CONSTRAINT chk_snapshot_calories_nonneg CHECK (calories_burned IS NULL OR calories_burned >= 0),
    CONSTRAINT chk_snapshot_hr_range        CHECK (heart_rate IS NULL OR (heart_rate >= 0 AND heart_rate <= 300))
);

CREATE INDEX idx_snapshot_user_time ON health_snapshots (user_id, recorded_at DESC);

COMMENT ON TABLE  health_snapshots                 IS '1분 polling 메트릭 시계열 (5분 batch append). 모든 메트릭 nullable — SDK가 일부만 반환할 수 있음';
COMMENT ON COLUMN health_snapshots.recorded_at     IS '클라이언트 측 측정 시각 (KST LocalDateTime)';
COMMENT ON COLUMN health_snapshots.steps_total     IS 'getTodaySteps() 누적값. counter-rate (MAX-MIN) 쿼리';
COMMENT ON COLUMN health_snapshots.calories_burned IS 'getTodayActiveCalories() 누적값. counter-rate 쿼리';
COMMENT ON COLUMN health_snapshots.heart_rate      IS 'getLatestHeartRate() 순간값(bpm). AVG/MIN/MAX 쿼리';
