-- =============================================================
-- V3: step_records 테이블 신설
--   - AI Agent의 시간대별 걸음수 조회용 시계열 저장
--   - 5분 배치 INSERT, ON CONFLICT (user_id, recorded_at) DO NOTHING
--   - Agent 쿼리: MAX(steps_total) - MIN(steps_total) (counter-rate 패턴)
-- =============================================================

CREATE TABLE step_records (
    id          BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     INT       NOT NULL,
    recorded_at TIMESTAMP NOT NULL,
    steps_total INT       NOT NULL,
    CONSTRAINT pk_step_records       PRIMARY KEY (id),
    CONSTRAINT uq_step_user_time     UNIQUE (user_id, recorded_at),
    CONSTRAINT fk_step_user          FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_step_total_nonneg CHECK (steps_total >= 0)
);

CREATE INDEX idx_step_user_time ON step_records (user_id, recorded_at DESC);

COMMENT ON TABLE  step_records             IS '걸음수 시계열 (5분 배치 append, getTodaySteps 누적값 그대로)';
COMMENT ON COLUMN step_records.recorded_at IS '클라이언트 측 측정 시각 (UTC TIMESTAMP)';
COMMENT ON COLUMN step_records.steps_total IS '오늘 누적 걸음수 (Samsung Health getTodaySteps)';
