-- =============================================================
-- V4: 타임라인 통합 조회용 테이블 4종 추가 [#294]
--   - glucose_records  : CGM 혈당 측정 시계열
--   - meal_records     : 식사 기록 (이벤트)
--   - exercise_records : 운동 세션 (이벤트)
--   - sleep_records    : 수면 세션 (이벤트)
-- 인덱스 설계는 docs/timeline-query-design.md 참조.
-- 도메인 스토리(CGM-BE/MEAL-BE/HEALTH-SYNC)에서 추후 컬럼/관계 확장은 V5+.
-- =============================================================

-- ────────────────────────────────────────────
-- glucose_records (CGM 혈당 측정값)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS glucose_records (
    id          BIGSERIAL      NOT NULL,
    user_id     BIGINT         NOT NULL,
    value       NUMERIC(5,2)   NOT NULL,
    measured_at TIMESTAMP      NOT NULL,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_glucose_records PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_glucose_user_time ON glucose_records (user_id, measured_at);

COMMENT ON COLUMN glucose_records.value       IS '혈당값 (mg/dL)';
COMMENT ON COLUMN glucose_records.measured_at IS 'CGM 디바이스가 측정한 시각 (서버 tz=KST)';

-- ────────────────────────────────────────────
-- meal_records (식사 기록)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS meal_records (
    id                INT            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT         NOT NULL,
    food_id           BIGINT         NULL,
    image_origin_name VARCHAR(255)   NULL,
    image_storage_key VARCHAR(255)   NULL,
    is_processed      BOOLEAN        NOT NULL DEFAULT FALSE,
    recorded_at       TIMESTAMP      NOT NULL,
    created_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_meal_records PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_meal_user_time ON meal_records (user_id, recorded_at);

COMMENT ON COLUMN meal_records.food_id           IS 'foods.id (수동 입력 시 NULL). FK는 foods 테이블 추가 후 별도 migration에서 부여';
COMMENT ON COLUMN meal_records.image_storage_key IS 'S3 등 외부 스토리지 키';
COMMENT ON COLUMN meal_records.recorded_at       IS '실제 식사 시각 (서버 tz=KST)';

-- ────────────────────────────────────────────
-- exercise_records (운동 세션)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS exercise_records (
    id            INT            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT         NOT NULL,
    exercise_type VARCHAR(20)    NOT NULL,
    calories      NUMERIC(6,2)   NULL,
    started_at    TIMESTAMP      NOT NULL,
    ended_at      TIMESTAMP      NOT NULL,
    created_at    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_exercise_records PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_ex_user_time ON exercise_records (user_id, started_at);

COMMENT ON COLUMN exercise_records.exercise_type IS 'WALKING / RUNNING / CYCLING 등';
COMMENT ON COLUMN exercise_records.calories      IS '소모 칼로리 (kcal)';

-- ────────────────────────────────────────────
-- sleep_records (수면 세션)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sleep_records (
    id         INT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT    NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at   TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sleep_records PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_sleep_user_time ON sleep_records (user_id, started_at);
