-- =============================================================
-- V4: alerts 테이블 신설 (Agent #6/#7 알림 입구 + 향후 룰 알림 공용 인프라)
--   - guardian_notifications, agent_pending_triggers, sleep_sessions는 M2에서 별도 추가
--   - alert_type은 VARCHAR(50)로 자유 — 룰(HIGH/LOW/SOS/WEEKLY_REPORT) + AGENT_* prefix
--   - source: 'rule' | 'agent' (어느 출처가 INSERT했는지 추적)
--   - 30분 dedup 윈도우 인덱스: (user_id, alert_type, resolved_at, created_at)
-- =============================================================

CREATE TABLE alerts (
    id                BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           INT          NOT NULL,
    alert_type        VARCHAR(50)  NOT NULL,
    glucose_record_id BIGINT       NULL,
    weekly_report_id  BIGINT       NULL,                 -- 향후 V7 weekly_reports 신설 시 FK 추가
    message           VARCHAR(500) NULL,
    source            VARCHAR(20)  NOT NULL DEFAULT 'rule',
    latitude          DOUBLE PRECISION NULL,
    longitude         DOUBLE PRECISION NULL,
    is_read           BOOLEAN      NOT NULL DEFAULT FALSE,
    resolved_at       TIMESTAMP    NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMP    NULL,
    CONSTRAINT pk_alerts                PRIMARY KEY (id),
    CONSTRAINT fk_alerts_user           FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_alerts_glucose        FOREIGN KEY (glucose_record_id) REFERENCES glucose_records (id),
    CONSTRAINT chk_alerts_source        CHECK (source IN ('rule', 'agent'))
);

CREATE INDEX idx_alerts_user_unread
  ON alerts (user_id, is_read, created_at DESC);

CREATE INDEX idx_alerts_dedup_window
  ON alerts (user_id, alert_type, resolved_at, created_at);

COMMENT ON TABLE  alerts             IS '알림 통합 테이블. 룰(BE)·agent 양쪽 INSERT';
COMMENT ON COLUMN alerts.alert_type  IS '룰: HIGH/LOW/SOS/WEEKLY_REPORT. agent: AGENT_* prefix';
COMMENT ON COLUMN alerts.source      IS 'rule=BE 룰 트리거, agent=Agent send_notification 호출';
COMMENT ON COLUMN alerts.resolved_at IS 'NULL이면 미해결. 정상 복귀 시 또는 사용자 응답 시 set';
