-- =============================================================
-- V5: 음식 검색 캐시 테이블 추가 [#297]
--   - foods : 식품안전처 API 응답 캐시 (영양성분, 검색 count)
--   - meal_records.food_id FK 제약 추가
-- =============================================================

-- ────────────────────────────────────────────
-- foods (식품안전처 API 캐시)
-- ────────────────────────────────────────────
CREATE TABLE foods (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    food_api_id VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL,
    kcal        NUMERIC(8,2) NULL,
    carbs_g     NUMERIC(8,2) NULL,
    sugar_g     NUMERIC(8,2) NULL,
    protein_g   NUMERIC(8,2) NULL,
    fat_g       NUMERIC(8,2) NULL,
    search_count INT          NOT NULL DEFAULT 0,
    cached_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_foods PRIMARY KEY (id),
    CONSTRAINT uq_foods_food_api_id UNIQUE (food_api_id)
);

CREATE INDEX idx_foods_name ON foods (name);
CREATE INDEX idx_foods_cached_at ON foods (cached_at);

COMMENT ON COLUMN foods.food_api_id   IS '식품안전처 API 식품코드 (FOOD_CD)';
COMMENT ON COLUMN foods.name          IS '음식명 (DESC_KOR)';
COMMENT ON COLUMN foods.kcal          IS '에너지 (kcal/100g)';
COMMENT ON COLUMN foods.carbs_g       IS '탄수화물 (g/100g)';
COMMENT ON COLUMN foods.sugar_g       IS '당류 (g/100g)';
COMMENT ON COLUMN foods.protein_g     IS '단백질 (g/100g)';
COMMENT ON COLUMN foods.fat_g         IS '지방 (g/100g)';
COMMENT ON COLUMN foods.search_count  IS '검색 히트 횟수';
COMMENT ON COLUMN foods.cached_at     IS '캐시 저장 시각 (30일 후 만료)';

-- ────────────────────────────────────────────
-- meal_records.food_id FK 제약 추가
-- ────────────────────────────────────────────
ALTER TABLE meal_records
    ADD CONSTRAINT fk_meal_food FOREIGN KEY (food_id) REFERENCES foods (id);
