-- =============================================================
-- V5: agent_pending_triggers 테이블 신설
--
-- 목적:
--   식사 기록(meal_records) 저장 시 "식후 1시간 뒤 AI Agent 호출"을
--   예약하기 위한 대기 큐 테이블.
--
--   BE 내부 스케줄러(@Scheduled)가 1분마다 이 테이블을 조회해
--   scheduled_at이 지난 미발송 트리거를 찾아 AI 서버에 HTTP POST로 전달.
--   AI 서버는 수동적으로 요청을 받아 처리(운동 권고 등)만 하면 됨.
--
-- 흐름:
--   POST /api/meals
--     → meal_records INSERT
--     → agent_pending_triggers INSERT (trigger_type='post_meal', scheduled_at=식사시각+60분)
--
--   @Scheduled (1분마다)
--     → SELECT WHERE scheduled_at <= NOW() AND is_dispatched = false
--     → 있으면 AI 서버 HTTP POST
--     → is_dispatched = true 업데이트
--
-- 확장성:
--   trigger_type 컬럼으로 향후 다른 트리거(post_exercise, bedtime 등)도 동일 테이블에서 관리.
--   is_processed(meal_records)는 "식후 혈당 반응 기록 완료 여부"로 의미가 다르므로 혼용 금지.
-- =============================================================

CREATE TABLE agent_pending_triggers (
    id            INT         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       INT         NOT NULL,
    trigger_type  VARCHAR(50) NOT NULL,
    reference_id  INT         NULL,
    scheduled_at  TIMESTAMP   NOT NULL,
    is_dispatched BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_agent_pending_triggers PRIMARY KEY (id),
    CONSTRAINT fk_trigger_user           FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 스케줄러 폴링용: 미발송 + 실행 예정 시각 기준 빠른 조회
CREATE INDEX idx_trigger_pending ON agent_pending_triggers (is_dispatched, scheduled_at);

COMMENT ON TABLE  agent_pending_triggers               IS 'BE 스케줄러가 AI 서버에 전달할 트리거 대기 큐';
COMMENT ON COLUMN agent_pending_triggers.trigger_type  IS 'post_meal — 식후 1시간 AI 운동/행동 권고 트리거';
COMMENT ON COLUMN agent_pending_triggers.reference_id  IS '트리거 원인 레코드 ID (post_meal이면 meal_records.id)';
COMMENT ON COLUMN agent_pending_triggers.scheduled_at  IS 'AI 서버 호출 예정 시각 (식사 recorded_at + 60분)';
COMMENT ON COLUMN agent_pending_triggers.is_dispatched IS 'AI 서버에 HTTP POST 전달 완료 여부';
