-- =============================================================
-- V9: sleep_sessions 테이블 신설
--
-- 목적:
--   하루 N개 수면 세션(메인 수면 + 낮잠) 정밀 저장.
--   기존 daily_health_summaries.sleep_minutes는 일별 합계 (대시보드/주간 차트용)로 유지.
--   본 테이블은 정규화된 1:N 원천 — Agent가 시작/종료 시각 기반 코칭 시 사용.
--
-- 트리거 연계:
--   세션 INSERT 시 agent_pending_triggers(trigger_type='wake_up', reference_id=session.id) 자동 INSERT.
--   폴러가 즉시(NOW()) 발화 → Agent가 기상 직후 코칭.
--
-- 중복 방지:
--   동일 사용자가 동일 started_at으로 두 번 INSERT 시도 시 unique 제약으로 차단.
--   FE 재동기화/재시도 안전.
-- =============================================================

CREATE TABLE sleep_sessions (
    id          INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     INT          NOT NULL,
    started_at  TIMESTAMP    NOT NULL,
    ended_at    TIMESTAMP    NOT NULL,
    source      VARCHAR(30)  NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_sleep_sessions       PRIMARY KEY (id),
    CONSTRAINT fk_sleep_sessions_user  FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_sleep_sessions_start UNIQUE (user_id, started_at),
    CONSTRAINT ck_sleep_sessions_range CHECK (ended_at > started_at)
);

CREATE INDEX idx_sleep_sessions_user_started ON sleep_sessions (user_id, started_at);

COMMENT ON TABLE  sleep_sessions             IS '워치/Health Connect에서 받은 개별 수면 세션 (메인 수면 + 낮잠)';
COMMENT ON COLUMN sleep_sessions.started_at  IS '수면 시작 시각 (워치 기준)';
COMMENT ON COLUMN sleep_sessions.ended_at    IS '수면 종료(기상) 시각';
COMMENT ON COLUMN sleep_sessions.source      IS '데이터 출처: samsung_health, health_connect, manual 등';
