-- =====================================================================
-- 현행 운영 스키마 (PostgreSQL, SOT)
-- ---------------------------------------------------------------------
-- 갱신일 : 2026-05-02
-- 용도   : 운영 DB의 단일 진실 원천(Source of Truth)
-- 출처   : 새 통합 V1 마이그레이션과 1:1 일치
--
-- ⚠️ 진실 원천 우선순위:
--   1. backend/src/main/resources/db/migration/V1__init_schema.sql (실제 적용)
--   2. JPA 엔티티 (com.ssafy.s309.domain.*.entity.*)
--   3. 본 ERD.sql (위 두 가지의 종합 뷰)
--
-- 📌 V6까지의 마이그레이션을 모두 비우고 통합 V1로 재구축한 결과 상태입니다.
--    이전 ERD에 있던 변경 예정 사항(ERD-02/03/04A/05)도 모두 통합 반영됨.
--
-- 🎨 시각화: 본 파일은 PostgreSQL DDL이라 ERD Cloud(MySQL 기반) 직접
--    임포트가 안 될 수 있음. dbdiagram.io 또는 DBeaver 권장.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. users  (회원)
--    이메일/소셜 가입, 온보딩 시 신체정보·당뇨유형·목표혈당 입력
--    deleted_at NOT NULL → 탈퇴 회원(소프트 삭제 + 익명화)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id              INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email           VARCHAR(255)    NOT NULL,                       -- 탈퇴 시 'deleted_{id}@withdrawn.local' 로 익명화
    password        VARCHAR(60)     NULL,                           -- BCrypt 해시. 소셜 로그인 시 NULL
    provider        VARCHAR(10)     NOT NULL DEFAULT 'email',       -- email / kakao / google
    name            VARCHAR(20)     NOT NULL,                       -- 한글 풀네임 + 영문 닉네임 수용
    age             SMALLINT        NULL,
    gender          VARCHAR(6)      NULL,                           -- male / female
    phone           VARCHAR(20)     NOT NULL,                       -- 국제번호, 하이픈 포함
    height          NUMERIC(4,1)    NULL,                           -- 키 (cm) — 예측 API용
    weight          NUMERIC(4,1)    NULL,                           -- 체중 (kg) — 예측 API용
    diabetes_type   VARCHAR(10)     NULL DEFAULT 'NORMAL',          -- NORMAL / T1D / T2D
    is_medicated    BOOLEAN         NULL,                           -- 당뇨약/인슐린 투약 대상자 여부
    target_low      NUMERIC(5,2)    NULL DEFAULT 70,                -- 목표 하한 혈당 (mg/dL)
    target_high     NUMERIC(5,2)    NULL DEFAULT 140,               -- 목표 상한 혈당 (mg/dL)
    week_start_day  SMALLINT        NOT NULL DEFAULT 1,             -- 다음 리포트 시작 요일 (1=월요일)
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP       NULL,                           -- 탈퇴 시각 (소프트 삭제)
    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);


-- ---------------------------------------------------------------------
-- 2. foods  (식약처 API 캐시 + 영양표시 9대 항목 + 식이섬유 + 식품 분류)
--    공공데이터포털 식품영양성분 API(FoodNtrCpntDbInfo02) 응답을 캐시.
--    영양성분은 모두 100g 또는 100ml 기준 (nutConSrtrQua 100 고정).
--    사용자 섭취량은 별도 기록 후 비례 계산.
--
--    저장 영양소: 식약처 영양표시 의무 9대 항목 + 식이섬유 = 10개
--      열량, 탄수화물, 당류, 단백질, 지방, 트랜스지방, 포화지방,
--      콜레스테롤, 나트륨, 식이섬유
-- ---------------------------------------------------------------------
CREATE TABLE foods (
    id                 INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    food_api_id        VARCHAR(64)  NULL,                        -- 식약처 식품코드 (foodCd)
    name               VARCHAR(100) NOT NULL,                        -- 음식명 (foodNm)
    category           VARCHAR(50)  NULL,                            -- 식품 대분류명 (foodLv3Nm) — 검색 카테고리/통계 그룹핑
    kcal               NUMERIC(6,2) NULL,                            -- 에너지 (kcal/100g, enerc)
    carbs_g            NUMERIC(5,2) NULL,                            -- 탄수화물 (g/100g, chocdf)
    sugar_g            NUMERIC(5,2) NULL,                            -- 당류 (g/100g, sugar)
    protein_g          NUMERIC(5,2) NULL,                            -- 단백질 (g/100g, prot)
    fat_g              NUMERIC(5,2) NULL,                            -- 지방 (g/100g, fatce)
    fiber_g            NUMERIC(5,2) NULL,                            -- 식이섬유 (g/100g, fibtg)
    saturated_fat_g    NUMERIC(5,2) NULL,                            -- 포화지방 (g/100g, fasat)
    trans_fat_g        NUMERIC(5,2) NULL,                            -- 트랜스지방 (g/100g, fatrn)
    cholesterol_mg     NUMERIC(5,2) NULL,                            -- 콜레스테롤 (mg/100g, chole)
    sodium_mg          NUMERIC(5,2) NULL,                            -- 나트륨 (mg/100g, nat)
    serving_size       NUMERIC(5,2) NULL,                            -- 1회 제공량 (100g or 100ml)
    is_customized      BOOLEAN      NOT NULL DEFAULT FALSE,          -- 사용자가 등록한 음식인지
    search_count       INT          NOT NULL DEFAULT 0,              -- 검색 히트 횟수 (캐시 우선순위)
    cached_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 식약처 API 마지막 호출 시각 (30일 TTL 기준)
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- search_count 등 모든 row 변경 시 갱신 (auto)
    CONSTRAINT pk_foods             PRIMARY KEY (id),
    CONSTRAINT uq_foods_food_api_id UNIQUE (food_api_id)
);
CREATE INDEX idx_foods_name      ON foods (name);
CREATE INDEX idx_foods_category  ON foods (category);
CREATE INDEX idx_foods_cached_at ON foods (cached_at);


-- ---------------------------------------------------------------------
-- 3. glucose_records  (CGM 혈당 측정 시계열)
--    BLE 5분 주기 수신. 5분 시계열이라 BIGINT.
--    🚧 수신 API 미구현 — docs/cgm-ingestion-status.md 참조
-- ---------------------------------------------------------------------
CREATE TABLE glucose_records (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     INT          NOT NULL,
    value       NUMERIC(5,2) NOT NULL,                              -- 혈당값 (mg/dL)
    measured_at TIMESTAMP    NOT NULL,                              -- CGM 디바이스 측정 시각 (서버 tz=KST)
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- 서버 기록 시각
    CONSTRAINT pk_glucose_records PRIMARY KEY (id),
    CONSTRAINT fk_glucose_user    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_glucose_user_time ON glucose_records (user_id, measured_at);


-- ---------------------------------------------------------------------
-- 4. meal_records  (식사 기록)
--    🚧 저장 API 미구현 — 엔티티/리포지토리만 존재
--    이 시점부터 2시간의 glucose_records를 시간 기준 조회 → 혈당 반응 분석
--    food_id NULL 허용: 사용자가 음식 검색 매칭 없이 수동 입력 가능
-- ---------------------------------------------------------------------
CREATE TABLE meal_records (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           INT          NOT NULL,
    food_id           INT          NULL,                            -- 수동 입력 시 NULL
    image_origin_name VARCHAR(255) NULL,                            -- 유저 업로드 원본 파일명
    image_storage_key VARCHAR(255) NULL,                            -- S3 등 외부 스토리지 키
    is_processed      BOOLEAN      NOT NULL DEFAULT FALSE,
    memo              VARCHAR(255) NULL,                            -- 메모
    recorded_at       TIMESTAMP    NOT NULL,                        -- 실제 식사 시각 (서버 tz=KST)
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_meal_records PRIMARY KEY (id),
    CONSTRAINT fk_meal_user    FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_meal_food    FOREIGN KEY (food_id) REFERENCES foods (id)
);
CREATE INDEX idx_meal_user_time ON meal_records (user_id, recorded_at);


-- ---------------------------------------------------------------------
-- 5. meal_glucose_responses  (식후 혈당 반응)
--    🚧 미구현 — 음식 성적표 의존 테이블
--    meal_records 1건당 1건 (1:1)
--    baseline / peak 는 glucose_records 의 특정 row 참조
--    최고혈당 값 자체는 peak_glucose_id 를 통해 glucose_records.value 조회
-- ---------------------------------------------------------------------
CREATE TABLE meal_glucose_responses (
    id                  INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id             INT          NOT NULL,
    meal_id             INT          NOT NULL,
    baseline_glucose_id BIGINT       NOT NULL,                      -- 식전 혈당 (FK → glucose_records.id)
    peak_glucose_id     BIGINT       NOT NULL,                      -- 식후 2시간 내 최고 혈당
    slope               NUMERIC(3,1) NOT NULL,                      -- 상승 기울기 (mg/dL/min) — 등급 산출 기준
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_meal_glucose_responses PRIMARY KEY (id),
    CONSTRAINT uq_response_meal     UNIQUE (meal_id),
    CONSTRAINT fk_response_user     FOREIGN KEY (user_id)             REFERENCES users (id),
    CONSTRAINT fk_response_meal     FOREIGN KEY (meal_id)             REFERENCES meal_records (id),
    CONSTRAINT fk_response_baseline FOREIGN KEY (baseline_glucose_id) REFERENCES glucose_records (id),
    CONSTRAINT fk_response_peak     FOREIGN KEY (peak_glucose_id)     REFERENCES glucose_records (id)
);
CREATE INDEX idx_response_user ON meal_glucose_responses (user_id);


-- ---------------------------------------------------------------------
-- 6. glucose_predictions  (식전 혈당 예측)
--    "이걸 먹으면 혈당이 어떻게 될까" AI 시뮬레이션 결과
--    A/B 비교 시에도 각각 저장됨 (히스토리)
-- ---------------------------------------------------------------------
CREATE TABLE glucose_predictions (
    id              INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id         INT          NOT NULL,
    food_id         INT          NULL,                              -- 음식 DB에 없는 데이터인 경우 NULL
    food_name       VARCHAR(100) NULL,                              -- food_id 없을 때 수기 입력
    predicted_curve JSON         NOT NULL,                          -- 예측 곡선 [{minuteOffset, glucoseMgdl}, ...]
    predicted_peak  NUMERIC(5,2) NULL,                              -- 예측 최고 혈당 (mg/dL)
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_glucose_predictions PRIMARY KEY (id),
    CONSTRAINT fk_prediction_user     FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_prediction_food     FOREIGN KEY (food_id) REFERENCES foods (id)
);
CREATE INDEX idx_prediction_user_time ON glucose_predictions (user_id, created_at);


-- ---------------------------------------------------------------------
-- 7. user_food_grades  (유저별 음식 성적표)
--    grade 5단계 (S/A/B/C/D)
--    ※ 최고혈당/복귀시간이 필요하면 meal_glucose_responses의
--      peak_glucose_id를 통해 glucose_records 와 join 해서 조회
-- ---------------------------------------------------------------------
CREATE TABLE user_food_grades (
    id         INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    INT          NOT NULL,
    food_id    INT          NOT NULL,
    avg_slope  NUMERIC(3,1) NOT NULL,                               -- meal_glucose_responses.slope 평균
    grade      CHAR(1)      NOT NULL,                               -- S / A / B / C / D
    meal_count INT          NOT NULL,                               -- 평균 산정에 사용된 식사 횟수
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_food_grades PRIMARY KEY (id),
    CONSTRAINT uq_user_food         UNIQUE (user_id, food_id),
    CONSTRAINT fk_grade_user        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_grade_food        FOREIGN KEY (food_id) REFERENCES foods (id),
    CONSTRAINT ck_user_food_grade   CHECK (grade IN ('S','A','B','C','D'))
);


-- ---------------------------------------------------------------------
-- 8. weekly_reports  (주간 리포트)
--    동기 생성 정책 (status 컬럼 없음, pdf_key NOT NULL)
-- ---------------------------------------------------------------------
CREATE TABLE weekly_reports (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           INT          NOT NULL,
    week_start        DATE         NULL DEFAULT CURRENT_DATE,       -- 리포트 커버 시작일
    avg_glucose       NUMERIC(5,2) NULL,                            -- 주간 평균 혈당 (mg/dL)
    min_glucose       NUMERIC(5,2) NULL,                            -- 주간 최저 혈당 (mg/dL)
    max_glucose       NUMERIC(5,2) NULL,                            -- 주간 최고 혈당 (mg/dL)
    glucose_sd        NUMERIC(5,2) NULL,                            -- 혈당 표준편차 (변동 폭)
    time_in_range     NUMERIC(5,2) NULL,                            -- 목표 범위 내 비율 TIR (%)
    time_above_range  NUMERIC(5,2) NULL,                            -- 고혈당 비율 TAR (%)
    time_below_range  NUMERIC(5,2) NULL,                            -- 저혈당 비율 TBR (%)
    ai_summary        TEXT         NULL,                            -- LLM 생성 주간 요약
    ai_suggest        TEXT         NULL,                            -- LLM 생성 개선 제안
    pdf_key           VARCHAR(100) NOT NULL,                        -- S3 PDF 키 (예: reports/user_1/week_1.pdf)
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_weekly_reports PRIMARY KEY (id),
    CONSTRAINT fk_report_user    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_report_user_week ON weekly_reports (user_id, week_start);


-- ---------------------------------------------------------------------
-- 9. weekly_foods  (주간 리포트의 GOOD/BAD 음식 목록)
--    image_storage_key NULL 허용 — 사용자가 사진 없이 검색만으로
--    식사 기록한 경우 NULL 가능
-- ---------------------------------------------------------------------
CREATE TABLE weekly_foods (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    report_id         INT          NOT NULL,
    food_id           INT          NOT NULL,
    type              VARCHAR(4)   NOT NULL,                        -- GOOD / BAD
    image_storage_key VARCHAR(255) NULL,                            -- 주 중 마지막에 먹은 음식 사진 (없을 수 있음)
    avg_slope         NUMERIC(3,1) NOT NULL,                        -- 해당 주 해당 음식 평균 기울기
    CONSTRAINT pk_weekly_foods       PRIMARY KEY (id),
    CONSTRAINT fk_weekly_food_report FOREIGN KEY (report_id) REFERENCES weekly_reports (id),
    CONSTRAINT fk_weekly_food_food   FOREIGN KEY (food_id)   REFERENCES foods (id),
    CONSTRAINT ck_weekly_food_type   CHECK (type IN ('GOOD','BAD'))
);
CREATE INDEX idx_weekly_food_report ON weekly_foods (report_id);


-- ---------------------------------------------------------------------
-- 10. notification_tokens  (FCM 푸시 토큰)
--    한 유저당 device_type 당 1개 유지 (갱신 정책)
--    device_type: 'ANDROID' / 'WATCH' (대문자 Java enum 표준)
-- ---------------------------------------------------------------------
CREATE TABLE notification_tokens (
    id          INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     INT          NOT NULL,
    token       VARCHAR(200) NOT NULL,                              -- FCM 토큰 값
    device_type VARCHAR(10)  NOT NULL DEFAULT 'ANDROID',
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,                 -- 로그아웃 시 false
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notification_tokens PRIMARY KEY (id),
    CONSTRAINT fk_noti_user           FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_noti_device_type    CHECK (device_type IN ('ANDROID','WATCH'))
);
CREATE INDEX idx_noti_user_active ON notification_tokens (user_id, is_active);


-- ---------------------------------------------------------------------
-- 11. alerts  (알림 기록)
--    alert_type 4종: HIGH(고혈당) / LOW(저혈당) / SOS / WEEKLY_REPORT
--    혈당 알림이면 glucose_record_id, 리포트 알림이면 weekly_report_id
-- ---------------------------------------------------------------------
CREATE TABLE alerts (
    id                INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           INT          NOT NULL,
    alert_type        VARCHAR(20)  NOT NULL,
    glucose_record_id BIGINT       NULL,                            -- HIGH/LOW/SOS 트리거 측정
    weekly_report_id  INT          NULL,                            -- 리포트 알림 대상
    message           VARCHAR(100) NULL,                            -- 알림 메시지 본문
    latitude          NUMERIC(9,6) NULL,                            -- SOS 발송 시 GPS 위도
    longitude         NUMERIC(9,6) NULL,                            -- SOS 발송 시 GPS 경도
    is_read           BOOLEAN      NOT NULL DEFAULT FALSE,          -- 읽음/안읽음 + SOS 미응답 에스컬레이션
    resolved_at       TIMESTAMP    NULL,                            -- 혈당 정상 복귀 / SOS 응답 / 사용자 확인
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMP    NULL,                            -- 소프트 삭제
    CONSTRAINT pk_alerts        PRIMARY KEY (id),
    CONSTRAINT fk_alert_user    FOREIGN KEY (user_id)           REFERENCES users (id),
    CONSTRAINT fk_alert_glucose FOREIGN KEY (glucose_record_id) REFERENCES glucose_records (id),
    CONSTRAINT fk_alert_report  FOREIGN KEY (weekly_report_id)  REFERENCES weekly_reports (id),
    CONSTRAINT ck_alerts_type   CHECK (alert_type IN ('HIGH','LOW','SOS','WEEKLY_REPORT'))
);
CREATE INDEX idx_alert_user_time ON alerts (user_id, created_at);


-- ---------------------------------------------------------------------
-- 12. ward_guardian  (피보호자-보호자 매핑)
--    같은 ward_id 내에서 priority 중복 금지 정책 (작을수록 우선)
--    ⏸️ UNIQUE(ward_id, priority) 제약은 보호자 모델 변경 작업과 함께 추후
-- ---------------------------------------------------------------------
CREATE TABLE ward_guardian (
    id          INT         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ward_id     INT         NOT NULL,                               -- 피보호자
    guardian_id INT         NOT NULL,                               -- 보호자
    relation    VARCHAR(10) NULL,                                   -- 부모 / 배우자 / 자녀 등
    priority    SMALLINT    NOT NULL,                               -- 0이 1순위 (SOS 연락 순서)
    CONSTRAINT pk_ward_guardian PRIMARY KEY (id),
    CONSTRAINT fk_wg_ward       FOREIGN KEY (ward_id)     REFERENCES users (id),
    CONSTRAINT fk_wg_guardian   FOREIGN KEY (guardian_id) REFERENCES users (id)
);
CREATE INDEX idx_wg_ward     ON ward_guardian (ward_id);
CREATE INDEX idx_wg_guardian ON ward_guardian (guardian_id);


-- ---------------------------------------------------------------------
-- 13. guardian_notifications  (보호자 SOS 발송 이력)
--    responded_at NULL이면 미응답 (에스컬레이션 판정 기준)
-- ---------------------------------------------------------------------
CREATE TABLE guardian_notifications (
    id                INT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    alert_id          INT       NOT NULL,                           -- 어떤 SOS인지
    guard_relation_id INT       NOT NULL,                           -- ward_guardian.id 참조
    sent_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- created_at 역할, 미응답 판정 기준
    responded_at      TIMESTAMP NULL,
    CONSTRAINT pk_guardian_notifications PRIMARY KEY (id),
    CONSTRAINT fk_gn_alert    FOREIGN KEY (alert_id)          REFERENCES alerts (id),
    CONSTRAINT fk_gn_relation FOREIGN KEY (guard_relation_id) REFERENCES ward_guardian (id)
);
CREATE INDEX idx_gn_alert    ON guardian_notifications (alert_id);
CREATE INDEX idx_gn_relation ON guardian_notifications (guard_relation_id);


-- ---------------------------------------------------------------------
-- 14. medications_records  (복약 기록)
--    약/인슐린 구분 없이 투약 여부만 기록 (memo 자유 기술)
-- ---------------------------------------------------------------------
CREATE TABLE medications_records (
    id         INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    INT          NOT NULL,
    memo       VARCHAR(200) NULL,                                   -- 약 이름, 세부사항 등 자유 기술
    taken_at   TIMESTAMP    NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_medications_records PRIMARY KEY (id),
    CONSTRAINT fk_med_user            FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_med_user_time ON medications_records (user_id, taken_at);


-- ---------------------------------------------------------------------
-- 15. sleep_records  (수면 세션)
-- ---------------------------------------------------------------------
CREATE TABLE sleep_records (
    id         INT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    INT       NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at   TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sleep_records PRIMARY KEY (id),
    CONSTRAINT fk_sleep_user    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_sleep_user_time ON sleep_records (user_id, started_at);


-- ---------------------------------------------------------------------
-- 16. exercise_records  (운동 세션)
-- ---------------------------------------------------------------------
CREATE TABLE exercise_records (
    id            INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       INT          NOT NULL,
    exercise_type VARCHAR(20)  NOT NULL,                            -- WALKING / RUNNING / CYCLING 등
    calories      NUMERIC(6,2) NULL,                                -- 소모 칼로리 (kcal)
    started_at    TIMESTAMP    NOT NULL,
    ended_at      TIMESTAMP    NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_exercise_records PRIMARY KEY (id),
    CONSTRAINT fk_ex_user          FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_ex_user_time ON exercise_records (user_id, started_at);


-- =====================================================================
-- 관계 요약
-- ---------------------------------------------------------------------
-- users (1) ──┬─ (N) glucose_records
--             ├─ (N) meal_records ──── (0..1) foods
--             ├─ (N) meal_glucose_responses ── (1) meal_records
--             │                              ├─ (1) glucose_records [baseline]
--             │                              └─ (1) glucose_records [peak]
--             ├─ (N) glucose_predictions ── (0..1) foods
--             ├─ (N) user_food_grades ── (1) foods
--             ├─ (N) weekly_reports ── (N) weekly_foods ── (1) foods
--             ├─ (N) notification_tokens
--             ├─ (N) alerts ── (0..1) glucose_records
--             │             └─ (0..1) weekly_reports
--             ├─ (N) ward_guardian [ward_id]
--             ├─ (N) ward_guardian [guardian_id]
--             ├─ (N) medications_records
--             ├─ (N) sleep_records
--             └─ (N) exercise_records
--
-- alerts (1) ──── (N) guardian_notifications ── (1) ward_guardian
-- =====================================================================
