spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/s309
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.ssafy.s309: DEBUG
    org.hibernate.SQL: DEBUG
